import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"], // Include necessary subsets
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Define font weights
  variable: "--font-poppins", // Define a custom variable for the font
});

export const metadata = {
  title: "Areno Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased bg-[#324671]`}
      >
        {children}
      </body>
    </html>
  );
}
